version: '1.0'

x-common: &common
    image: ghcr.io/MatKos169/StreamlinkContainer:1.0
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
        # - ../global.env    
        - default.env
        - clientid.env
    user: 1027:100
    logging:
      driver: json-file
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
    volumes:
    - /volume1/twitch:/app/download

services:
  streamlink:
    <<: *common
    container_name: streamlink_${TWITCH}
    environment:
      - user=${TWITCH}
      - quality=best

  streamlink-latest:
    <<: *common
    container_name: streamlink-latest_${TWITCH}
    image: ghcr.io/MatKos169/StreamlinkContainer:latest
    environment:
      - user=${TWITCH}
      - quality=best